In [1]:
# Autograd used to calculate gradients. Gradients are used for model optimization 
import torch

In [15]:
x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.4453, 0.4500, 0.4941], requires_grad=True)


In [16]:
y = x + 2
print(y)

tensor([2.4453, 2.4500, 2.4941], grad_fn=<AddBackward0>)


In [17]:
z = y * y * 2
print(z)

tensor([11.9588, 12.0053, 12.4414], grad_fn=<MulBackward0>)


In [18]:
z = z.mean()
print(z)

tensor(12.1352, grad_fn=<MeanBackward0>)


In [19]:
z.backward() # dz/dx
print(x.grad)

tensor([3.2604, 3.2667, 3.3255])
