In [2]:
import torch

In [3]:
torch.cuda.is_available()

True

In [4]:
x = torch.rand([3])

In [5]:
x

tensor([0.3184, 0.4409, 0.6194])

In [7]:
# 1d vector

x = torch.empty(4)
print(x)

tensor([3.4985e+03, 3.0785e-41, 3.1629e+03, 3.0785e-41])


In [9]:
# 2d vector or matrix

x = torch.empty(2,3)
print(x)

tensor([[3.1628e+03, 3.0785e-41, 4.4096e+02],
        [4.5780e-41, 8.9683e-44, 0.0000e+00]])


In [11]:
# 3d tensor
x = torch.empty(3,3,2)
print(x)

tensor([[[ 4.4097e+02,  4.5780e-41],
         [ 3.2365e+03,  3.0785e-41],
         [ 4.4842e-44,  0.0000e+00]],

        [[ 1.5695e-43,  0.0000e+00],
         [ 2.8702e-24,  3.0789e-41],
         [ 0.0000e+00,  0.0000e+00]],

        [[ 4.7561e+03,  3.0785e-41],
         [ 1.0425e+03,  3.0785e-41],
         [-2.6319e-21,  4.5779e-41]]])


In [14]:
# 4d tensor
x = torch.empty(2,3,3,2)
print(x)

tensor([[[[1.0268e-08, 1.0674e-08],
          [5.3221e-05, 1.4580e-19],
          [1.1495e+24, 3.0881e+29]],

         [[1.5766e-19, 7.3313e+22],
          [7.2151e+22, 2.8404e+29],
          [2.3089e-12, 1.9421e+31]],

         [[2.7491e+20, 6.1949e-04],
          [1.0382e+21, 2.7256e+20],
          [2.3080e-12, 7.1760e+22]]],


        [[[7.2250e+28, 1.5766e-19],
          [2.6845e+23, 1.6838e+22],
          [4.1907e+21, 6.7197e-07]],

         [[4.2002e-08, 4.1022e-08],
          [8.5454e-07, 8.3813e-10],
          [2.3050e-12, 2.6302e+20]],

         [[6.1949e-04, 6.4805e-10],
          [2.5203e-09, 2.5928e-09],
          [6.8357e-04, 1.7340e-07]]]])


In [15]:
x = torch.ones(2,2, dtype=torch.double)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [17]:
print(x.size())

torch.Size([2, 2])


In [18]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [19]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.7425, 0.4683],
        [0.5505, 0.2539]])
tensor([[0.4663, 0.7838],
        [0.0581, 0.6330]])


In [21]:
# addition of two tensor

z = x + y # torch.add(x,y)
print(z)

tensor([[1.2088, 1.2521],
        [0.6086, 0.8869]])


In [22]:
y.add_(x) # added x to y and now y is modifies
print(y) 

tensor([[1.2088, 1.2521],
        [0.6086, 0.8869]])


In [23]:
z = x * y # or torch.mul(x,y)
z = x / y # or torch.div(x,y)

tensor([[0.8976, 0.5863],
        [0.3350, 0.2252]])


In [24]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4593, 0.9883, 0.9714],
        [0.9671, 0.0686, 0.1973],
        [0.4746, 0.3532, 0.6010],
        [0.4057, 0.5209, 0.2540],
        [0.0081, 0.8096, 0.7337]])


In [37]:
print(x[1:4,0:2])

tensor([[0.9671, 0.0686],
        [0.4746, 0.3532],
        [0.4057, 0.5209]])


In [38]:
x = torch.rand(5,3)
x = x.view(1,15)
print(x)

tensor([[0.0339, 0.7003, 0.8970, 0.0538, 0.8693, 0.6959, 0.2815, 0.0093, 0.3167,
         0.5673, 0.2697, 0.8987, 0.8317, 0.8950, 0.0814]])


In [44]:
# on CPU matmul of 10000 x 10000

x = torch.rand(10000,10000)
y = torch.rand(10000,10000)
%time z = torch.matmul(x,y)

CPU times: user 30.6 s, sys: 79.9 ms, total: 30.7 s
Wall time: 7.67 s


In [48]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.rand(10000,10000).to(device)
    y = torch.rand(10000,10000).to(device)
    %time z = torch.matmul(x,y)
    z = z.to("cpu")
    

CPU times: user 0 ns, sys: 807 µs, total: 807 µs
Wall time: 811 µs
